# Generated by Django 5.2.4 on 2025-08-13 12:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
