# Generated by Django 5.2.5 on 2025-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_offer_name_orderitem_name_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_confirmed',
            field=models.BooleanField(default=True, verbose_name='Est confirmé'),
        ),
    ]
