# Generated by Django 5.2.5 on 2025-10-17 13:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_order_is_confirmed'),
        ('products', '0008_alter_offer_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_suffix', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Suffixe du billet')),
                ('final_key', models.CharField(editable=False, max_length=200, unique=True)),
                ('qr_code', models.ImageField(help_text='Image PNG générée à partir de la clé finale.', upload_to='tickets/', verbose_name='QR Code')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='products.offer', verbose_name='Offre liée au billet')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order', verbose_name='Commande liée au billet')),
            ],
            options={
                'verbose_name': 'Billet',
                'verbose_name_plural': 'Billets',
                'ordering': ['-created_at'],
            },
        ),
    ]
