# Generated by Django 5.2.5 on 2025-10-20 16:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='unique_suffix',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
