# Generated by Django 5.2.5 on 2025-08-28 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, help_text="Ajoutez une description de l'offre (optionnel)."),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Cochez la case si l'offre est en vente.", verbose_name='Est en vente'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sales',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nombre de ventes'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seats',
            field=models.PositiveSmallIntegerField(default=1, help_text="Précisez le nombre de places associées à l'offre.", validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='slug',
            field=models.SlugField(help_text="La valeur se remplit automatiquement en renseignant le nom de l'offre.", max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text="Ajoutez une image qui représente l'offre (optionnel).", null=True, upload_to='products', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de la dernière mise à jour'),
        ),
    ]
