# Generated by Django 5.2.5 on 2025-08-28 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_offer_created_at_alter_offer_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='thumbnail',
        ),
    ]
