# Generated by Django 5.2.5 on 2025-08-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_offer_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(help_text="Ajoutez une description de l'offre."),
        ),
    ]
