# Generated by Django 5.2.5 on 2025-08-29 19:21

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_offer_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, message='Le prix doit être au moins de 0,01€.')], verbose_name='Prix'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='seats',
            field=models.PositiveSmallIntegerField(default=1, help_text="Précisez le nombre de places associées à l'offre.", validators=[django.core.validators.MinValueValidator(1, message='Nombre de places minimum : 1')], verbose_name='Nombre de places'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Date de la dernière mise à jour'),
            preserve_default=False,
        ),
    ]
