# Generated by Django 5.2.5 on 2025-09-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_offer_price_alter_offer_seats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='thumbnail',
            field=models.ImageField(default=2, upload_to='images/'),
            preserve_default=False,
        ),
    ]
