# Generated by Django 5.2.5 on 2025-09-25 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_offer_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
    ]
