# Generated by Django 5.2.5 on 2025-09-25 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_offer_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
