# Generated by Django 5.2.5 on 2025-10-21 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_offer_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='sales',
            field=models.PositiveIntegerField(default=0, verbose_name='Nombre de ventes'),
        ),
    ]
